### ISSUE TITLE
这个怎么使用

### ISSUE THREAD

**Issue by mckuhei** [GangZhuo/TrafficStatistics#1]
你好，这个要怎么搭建服务端啊

**Comment by GangZhuo** [comment]
这和翻墙无关，只是一个端口转发工具。我当时写他的目的是为了做一些网络数据分析。现在只是当作端口转发工具来用。例如公司网络禁止了桥接，虚拟机只能使用 Nat 网络，想让外部主机访问虚拟机的话，可以把母机的端口映射到虚拟机上。有很多工具都能达到这个目的的，我只是用顺手了。
